### PR TITLE
Pluggable wipe config

### PR DESCRIPTION
**Pull request by AadamZ5**
Matching by regular expressions will allow for configurable language options. Could address #35 and #15 

This PR aims to add:
- Matching by regex
- Extendable config file (support custom "languages")

Might need some help with tests.

### CODE REVIEW

**Comment by AadamZ5** [comment]
The config is working at this point, but is not yet integrated into unit tests, or integration tests. I'll need more time to get a grip on whats going on there.

**Comment by mihai-dinculescu** [comment]
Thank you for looking into this, @AadamZ5. The wipe config can definitely do with some love.

Here are some suggestion/questions:
1. Does the regex has to be mandatory? The 2 languages currently implemented don't make use of it and will get slowed down needlessly. 
2. It would be nice to have `target_folder` as optional. Some languages (Python comes to mind - it's the next language I was planning to add support for) don't have a pattern.
3. Saving/serializing the config is a very interesting idea, but maybe it would be best if it's discussed/done in a separate issue/PR so that it doesn't distract from the config rework.

**Comment by AadamZ5** [comment]
> 1. Does the regex has to be mandatory? The 2 languages currently implemented don't make use of it and will get slowed down needlessly.

I resorted to Regex with the thought of "custom" languages requiring complex matching semantics. I did think that it may be nice to support a simpler matching method, perhaps such as plain-string matching, but I think that would require the config file to become more verbose if we're to support both matching mechanisms. Definitely open to more thought here.

> 2. It would be nice to have `target_folder` as optional. Some languages (Python comes to mind - it's the next language I was planning to add support for) don't have a pattern.

This is interesting and I definitely didn't imagine a case like this. If the target folder is optional, how do we decide the thing we are deleting? If you have time, maybe a quick example of the Python package structure you're mentioning would help me understand this use case better. Although I have used Python, I haven't had the need to explore the package structure yet. `pip` and managers like `poetry` have been *magic* to me so far lol.

> 3. Saving/serializing the config is a very interesting idea, but maybe it would be best if it's discussed/done in a separate issue/PR so that it doesn't distract from the config rework.

That makes sense. This PR draft did manage to include a serialization implementation, but I see how decoupling our config decisions from the serialization process might let us explore more. I'd advocate for hard-coding a sane default config (like done in this PR) though. Maybe we should keep serialization in the back of our heads though as to not create an overly complex serialization effort later. 


Thanks for taking a look! With a bit more discussion I think I could push some changes.

**Comment by mihai-dinculescu** [comment]
I'm not personally aware of a situation where regex for `target_folder` is required. Do you have one in mind?

Python virtual envs can have an arbitrary name. The best way I can think of to identify them is to look inside any folder for a `pyvenv.cfg` file. For extra strength, we could also look for `lib` and `bin` folders (`Lib` and `Scripts` for Windows) inside, but I think that it's probably overkill.

**Comment by AadamZ5** [comment]
>I'm not personally aware of a situation where regex for `target_folder` is required. Do you have one in mind?

Ah, I think I sort of had some tunnel vision with depending on folders. The code I edited used `DirectoryEnum` in many places and I let myself be boxed into the idea of deleting folders. I think this is what you're getting at. As far as Regex, I'm just leaning on the fact that *somebody somewhere* will need really niche matching logic, and I feel like Regex is the best chance at solving that. Perhaps someone needs to delete a folder with some unknown date at the end. Regex will solve that. I'm trying to allow for the most flexibility to decrease support needed and increase adoption. 

`target_folder` might better be renamed as `target`, with the condition that a valid target could be a folder or a file. I think my current changes in `is_valid_target(...)` actually work that way anyways, but in `get_paths_to_delete(...)` there is a check that the current file is a directory. We can of course change this.
https://github.com/AadamZ5/cargo-wipe/blob/pluggable-wipe-config/src/dir_helpers.rs#L139

>Python virtual envs can have an arbitrary name. The best way I can think of to identify them is to look inside any folder for a `pyvenv.cfg` file. For extra strength, we could also look for `lib` and `bin` folders (`Lib` and `Scripts` for Windows) inside, but I think that it's probably overkill.

In the Python case, you'd like `target` to be optional (cause we don't know the virtual env folder name), and infer the target to delete from `target_folder_contains` and `parent_folder_contains`? 

Also side note about `lib` + `bin` vs `Lib` + `Scripts` on Windows, Regex seems like an appropriate tool to use here to deal with this slight naming variance. I still agree that we should prioritize a simpler matching method first as well. 

-------

Once we narrow in on a better config structure, I plan to close this PR draft and open a new one, unless you plan to begin development on this repo. Thanks for taking the time to discuss this with me, it's proving fun! And thanks for making this neat tool!

**Comment by mihai-dinculescu** [comment]
> Is this usable yet? I'd love to be able to wipe al `target*` directories as I have my editor configured to use a different than default target directory (to prevent conflicting locks when running multiple cargo processes at the same time)

That's not something I've considered until now. Thank you for pointing it out!
It looks like regex is the way to go, but I would still like to do some benchmarking first.

**Pull request closed without merging**
